builds:
- goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    amd64: 64-bit
  format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: false
  files:
  - none*
release:
  draft: true
